language: python
python:
- "3.7"
before_install:
- pip install setuptools>=60.5.0  # travis build seems to fail otherwise
install:
- pip install .
- pip list # list installed package versions
script:
- pytest -m "not requires_gpu and not memory_intense and not slow and not travis_slow"
